name: run-template-dapp-nextjs-integration

on:
  push:
    # TODO [development]
    branches: [main]
  repository_dispatch:
    types: run-template-dapp-nextjs-integration
  workflow_dispatch:

jobs:
  run_template_dapp_nextjs_integration_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Run script file
        run: |
          chmod +x ./scripts/template-dapp-nextjs-integration.sh
          ./scripts/template-dapp-nextjs-integration.sh
        shell: bash