name: run-template-dapp-integration

on:
  push:
    # TODO [development]
    branches: [main]
  repository_dispatch:
    types: run-template-dapp-integration
  workflow_dispatch:

jobs:
  run_template_dapp_integration_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Run script file
        run: |
          chmod +x ${GITHUB_WORKSPACE}/../.github/scripts/template-dapp-integration.sh
          ${GITHUB_WORKSPACE}/../.github/scripts/template-dapp-integration.sh
        shell: bash